name: Release Service
on:
  push:
    branches:
      - main
    # paths:
    #   - src
    #   - tests

jobs:
  service-tests:
    name: Test service
    runs-on: ubuntu-latest

    permissions:
      contents: "read"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry export --without-hashes --with dev --format=requirements.txt --output requirements.txt
          pip install -r requirements.txt

      - name: Check Linter
        run: |
          make linter

      - name: Check Formater
        run: |
          make format-check

      - name: Run Tests
        run: |
          make test

  service-build-and-deploy:
    name: Build And Deploy Service
    runs-on: ubuntu-latest
    needs: service-tests

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: |
            application:latest

  service-tag-and-release:
    name: Release Tag And Service
    runs-on: ubuntu-latest
    needs: service-build-and-deploy

    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - id: tag_version
      #   name: Bump version and push tag
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     custom_tag: ${{ needs.service-build-and-deploy.outputs.tag }}
      #     tag_prefix:

      # - id: github_release
      #   name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ needs.service-build-and-deploy.outputs.description }}
